debug YQ install

diff --git a/.github/workflows/github-ci.yml b/.github/workflows/github-ci.yml
--- a/.github/workflows/github-ci.yml
+++ b/.github/workflows/github-ci.yml
@@ -151,19 +151,21 @@ jobs:
       - name: Get version from file
         id: get_version
         run: echo "VERSION=$(cat .version)" >> $GITHUB_OUTPUT
-      - name: Install yq
-        run: |
-          # wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O ./yq
-          # chmod +x ./yq
-          # sudo mv ./yq /usr/local/bin/yq
-          if ! command -v yq &> /dev/null; then
-            echo "yq not found. Installing..."
-            wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O ./yq
-            chmod +x ./yq
-            sudo mv ./yq /usr/local/bin/yq
-          else
-            echo "yq is already installed."
-          fi
+
+
+      # - name: Install yq
+      #   run: |
+      #     # wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O ./yq
+      #     # chmod +x ./yq
+      #     # sudo mv ./yq /usr/local/bin/yq
+      #     if ! command -v yq &> /dev/null; then
+      #       echo "yq not found. Installing..."
+      #       wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O ./yq
+      #       chmod +x ./yq
+      #       sudo mv ./yq /usr/local/bin/yq
+      #     else
+      #       echo "yq is already installed."
+      #     fi
 
 
       - name: Perform health checks
